Fixed the spellchecker view as per tinymce doc
jazzband/django-tinymce pull request #373
Opened 2021-10-31 21:52 UTC by tazahmd

The spell checker was not conforming as per the [documentation](https://www.tiny.cloud/docs/plugins/opensource/spellchecker/#spellcheckerresponseformat).  

Update the spell checker view to support it

Note:
The data received is in post as querystring .
Stripping out spaces and ` . , : ; ' " ` at the end and start of any word.

2021-11-01 14:24 UTC, claudep commented
Apparently, some work is needed regarding tests.

By the way, a preliminary commit or PR should be transforming some HttpResponse's into JsonResponse's.

2021-11-01 17:11 UTC, tazahmd commented
@claudep: should the test be updated or some changes form the views.py side? 

Also, When you say convert HTTP response into JSON response. I m not sure which place should the change be applied.


I see this check in the test has failed, Is tinymce expecting a JSON or a HTML response?
https://github.com/jazzband/django-tinymce/blob/cec71245d14426bd45f10c6daae0650f9dd82c67/tests/test_views.py#L75

2021-11-01 21:26 UTC, claudep commented
I created #374 for the JsonResponse change.

> I see this check in the test has failed, Is tinymce expecting a JSON or a HTML response?

The response is (currently) a simple string when an error occurs in the spellcheck view, and a JSON response when the spellcheck succeeds in returning something. But you might change this in your patch. The tests most probably need to be changed to reflect the new expected response format.

2021-11-02 16:25 UTC, tazahmd commented
@claudep : pulled in #374 and updated the test as well.

2021-11-03 07:40 UTC, claudep commented
Thanks, I'll try to do a detail review during the next days.

2021-11-03 14:31 UTC, tazahmd commented
If you need to make changes feel free to push changes to this branch.

2021-11-05 17:14 UTC, claudep requested changes
Some small things... It looks in good shape now, thanks!

2021-11-05 17:14 UTC, claudep commented on tinymce/views.py
> +        lang = request.POST.get("lang", None)
AFAIK, you can omit the `None` part, as it is the default return value if the key is not found.

2021-11-05 17:14 UTC, claudep commented on tinymce/views.py
> +            raise Exception(e_msg)
I suggest returning always the same exception, RuntimeError or Exception, even if the exception type does not matter much here.

2021-11-05 17:14 UTC, claudep commented on tinymce/views.py
> +        output = {"error": e_msg}
Would be a bit cleaner to catch the exception message:
```
except Exception as err:
    output = {"error": str(err)}
```
but then the generic error message will not be used (not so useful IMHO).

2021-11-05 17:14 UTC, claudep commented on tests/test_views.py
> +import urllib
Let's import `from urlllib.parse import urlencode`, and then use only `urlencode` below.

2021-11-05 17:15 UTC, claudep commented
And please fix also the two flake8 warnings (see Lint build).

2021-11-05 17:16 UTC, claudep commented
And unfortunately, it looks like TinyMCE 6 will drop the spellchecker plugin... commercial model and all that :-(

2021-11-05 19:00 UTC, tazahmd commented on tests/test_views.py
> +import urllib
Implemented

2021-11-05 19:00 UTC, tazahmd commented on tinymce/views.py
> +        lang = request.POST.get("lang", None)
Removed the None

2021-11-05 19:01 UTC, tazahmd commented on tinymce/views.py
> +            raise Exception(e_msg)
Updated the exception to return `RuntimeError`

2021-11-05 19:01 UTC, tazahmd commented on tinymce/views.py
> +        output = {"error": e_msg}
Implemented as suggested

2021-11-05 19:28 UTC, tazahmd commented
Have implemented all your comments,

And Yeah! Tiny 6 will not have Free spell check plugin, maybe we have to stick to browser spellcheck for future releases.
We can implement for SpellcheckPro Plugin if demand arises.

2021-11-08 09:25 UTC, claudep commented
All tests pass now, nice! Could you please now rebase the branch and resolve conflicts? It would be great to add also a note in the Changelog about this spellchecker fix.

2021-11-08 17:36 UTC, tazahmd commented
@claudep rebased the branch and added a note to the changelog.rst

2021-11-09 14:55 UTC, claudep commented
I made some small fixes in #378.

2021-11-09 14:55 UTC, closed without merging