Switch to using proper staticfiles_storage.url() call to reference the TinyMCE JS
jazzband/django-tinymce pull request #425
Opened 2023-02-06 14:36 UTC by jameyg

To fix issue 420: https://github.com/jazzband/django-tinymce/issues/420

2023-02-06 15:55 UTC, merwok approved these changes

2023-02-06 21:21 UTC, claudep requested changes
Thanks! You can also include the "Fixes #420" either in the commit message or in the second line of the commit so that the issue will be automatically closed.

2023-02-06 21:21 UTC, claudep commented on tinymce/settings.py
>  import os
I think that import can be removed.

2023-02-16 17:29 UTC, jameyg commented
@claudep I've amended the commit message to included "Fixes #420" and removed the redundant `import os` call :+1:

2023-02-16 19:15 UTC, claudep approved these changes

2023-02-16 19:16 UTC, merged

2023-02-16 19:17 UTC, claudep commented
Thanks!